apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "auth-service.selectorLabels" . | nindent 4 }}
    app: auth-service
